//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGuestFeedback
    {
        public int feedback_id { get; set; }
        public string guest_phone_number { get; set; }
        public string feedback_content { get; set; }
        public Nullable<System.DateTime> date_submitted { get; set; }
        public string guest_email { get; set; }
    
        public virtual tblGuest tblGuest { get; set; }
    }
}
