//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGuest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGuest()
        {
            this.tblGuestFeedbacks = new HashSet<tblGuestFeedback>();
        }
    
        public string guest_phone_number { get; set; }
        public string guest_name { get; set; }
        public Nullable<System.DateTime> time_arrived { get; set; }
        public Nullable<int> num_of_guests { get; set; }
        public int table_num { get; set; }
        public string reservation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGuestFeedback> tblGuestFeedbacks { get; set; }
        public virtual tblUsedTable tblUsedTable { get; set; }
    }
}
